<?php 
# DATOS DE CONFIGURACIÓN
$FACTRONICA["DIRTXTPLANO"]="txt";
$FACTRONICA["TXTPLANO"]="librocompras.txt";
$FACTRONICA["DIRXMLLIBRO"]="xml_librocompra";
$FACTRONICA["XMLLIBRO"]="LIBROCOMPRAS_2016_12.xml";
$FACTRONICA["URLSERVIDOR"]="http://www.factronica.cl/servidores/servidor_v727"; 
$FACTRONICA["SCRIPTSERVIDOR"]="recibe_txt_librocompra.php"; 
$FACTRONICA["TOKEN"]="8Y89Y7B8";
$FACTRONICA["FOLDERFILES"]="xml_librocompra";
$FACTRONICA["TRACKID"]="trackid_librocompras_201608.xml";
# DATOS DE CONFIGURACION
$Config["Produccion"]="1";
$Config["EnviarSii"]="0";
$Config["EnviarMail"]="1";
$Config["MailDestino"]="contacto@factronica.cl";
# DATOS DE CARATULA
$Caratula["RutEmisorLibro"]="3728040-2";
$Caratula["RutEnvia"]="3728040-2";
$Caratula["PeriodoTributario"]="2016-09";
$Caratula["FchResol"]="2014-08-22";
$Caratula["NroResol"]="80";
$Caratula["TipoOperacion"]="";
$Caratula["TipoLibro"]="";
$Caratula["TipoEnvio"]="";
$Caratula["NroSegmento"]="";
$Caratula["FolioNotificacion"]="";
$Caratula["CodAutRec"]="";
# DATOS DOCUMENTO 1
$Detalle["TpoDoc"]["1"]="33";
$Detalle["NroDoc"]["1"]="123456";
$Detalle["TpoImp"]["1"]="1";
$Detalle["TasaImp"]["1"]="19";
$Detalle["FchDoc"]["1"]="2016-09-30";
$Detalle["CdgSIISucur"]["1"]="12312";
$Detalle["RUTDoc"]["1"]="90060000-3";
$Detalle["RznSoc"]["1"]="COMPAÑIA MOLINERA SAN CRISTOBALS.A";
$Detalle["TpoDocRef"]["1"]="";
$Detalle["FolioDocRef"]["1"]="";
$Detalle["MntExe"]["1"]="0";
$Detalle["MntNeto"]["1"]="100000";
$Detalle["MntIVA"]["1"]="19000";
$Detalle["IVARetTotal"]["1"]="";
$Detalle["CodIVANoRec"]["1"]="";
$Detalle["MntIVANoRec"]["1"]="";
$Detalle["IVAUsoComun"]["1"]="";
$Detalle["MntSinCred"]["1"]="";
$Detalle["MntTotal"]["1"]="131000";
$DetalleOtrosImp["CodImp"]["1"]["1"]="19";
$DetalleOtrosImp["TasaImp"]["1"]["1"]="12";
$DetalleOtrosImp["MntImp"]["1"]["1"]="12000";
# DATOS DEL RESUMEN
$Resumen["TpoDoc"]["33"]="33";
$Resumen["TpoImp"]["33"]="1";
$Resumen["TotDoc"]["33"]="79";
$Resumen["TotAnulado"]["33"]="";
$Resumen["TotOpExe"]["33"]="";
$Resumen["TotMntExe"]["33"]="0";
$Resumen["TotMntNeto"]["33"]="100000";
$Resumen["TotOpIVARec"]["33"]="";
$Resumen["TotMntIVA"]["33"]="19000";
$Resumen["TotOpActivoFijo"]["33"]="";
$Resumen["TotMntActivoFijo"]["33"]="";
$Resumen["TotMntIVAActivoFijo"]["33"]="";
$Resumen["TotIVANoRec"]["33"]="";
$Resumen["CodIVAnoRec"]["33"]="";
$Resumen["TotOpIVANoRec"]["33"]="";
$Resumen["TotMntIVANoRec"]["33"]="";
$Resumen["TotOpIVAusoComun"]["33"]="";
$Resumen["TotIVAUsoComun"]["33"]="";
$Resumen["FctProp"]["33"]="";
$Resumen["TotCrediIVAUsoComun"]["33"]="";
$Resumen["FctImpAdic"]["33"]="";
$Resumen["TotCredImp"]["33"]="";
$Resumen["TotImpSinCred"]["33"]="";
$Resumen["TotMntTotal"]["33"]="131000";
$Resumen["TotIVANoRetenido"]["33"]="";
$Resumen["TotTabPuros"]["33"]="";
$Resumen["TotTabCigarrillos"]["33"]="";
$Resumen["TotTabElaborado"]["33"]="";
$Resumen["TotImpVehiculo"]["33"]="";
$Resumen["CodImp"]["33"]["1"]="19"; // CODIGO OTROS IMPUESTOS
$Resumen["TotMntImp"]["33"]["1"]="12000"; // TOTAL IMPUESTO ADICIONAL DEL CODIGO INFORMADO EN CodImp
?>
